/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author cipri
 */
public class FormTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormTelaPrincipal
     */
    public FormTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastrar = new javax.swing.JMenu();
        MICadastrar = new javax.swing.JMenuItem();
        MenuPesquisar = new javax.swing.JMenu();
        MIPesquisar = new javax.swing.JMenuItem();
        MenuAlugar = new javax.swing.JMenu();
        MIAlugar = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        MISair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/livros.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        MenuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/salvar.png"))); // NOI18N
        MenuCadastrar.setText("Cadastrar");

        MICadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MICadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/cadastrarItem.png"))); // NOI18N
        MICadastrar.setText("Cadastrar Livro");
        MICadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadastrarActionPerformed(evt);
            }
        });
        MenuCadastrar.add(MICadastrar);

        jMenuBar1.add(MenuCadastrar);

        MenuPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/pesquisar.png"))); // NOI18N
        MenuPesquisar.setText("Pesquisar");

        MIPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MIPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/pesquisarItem.png"))); // NOI18N
        MIPesquisar.setText("Pesquisar Livros");
        MenuPesquisar.add(MIPesquisar);

        jMenuBar1.add(MenuPesquisar);

        MenuAlugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/alugar.png"))); // NOI18N
        MenuAlugar.setText("Alugar");

        MIAlugar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MIAlugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/alugarItem.png"))); // NOI18N
        MIAlugar.setText("Alugar Livro");
        MenuAlugar.add(MIAlugar);

        jMenuBar1.add(MenuAlugar);

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/sair.png"))); // NOI18N
        MenuSair.setText("Sair");

        MISair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MISair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/sair.png"))); // NOI18N
        MISair.setText("Sair");
        MISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISairActionPerformed(evt);
            }
        });
        MenuSair.add(MISair);

        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void MISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISairActionPerformed
        this.dispose();
    }//GEN-LAST:event_MISairActionPerformed

    private void MICadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadastrarActionPerformed
        new FormTelaCadastro().setVisible(true);
    }//GEN-LAST:event_MICadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIAlugar;
    private javax.swing.JMenuItem MICadastrar;
    private javax.swing.JMenuItem MIPesquisar;
    private javax.swing.JMenuItem MISair;
    private javax.swing.JMenu MenuAlugar;
    private javax.swing.JMenu MenuCadastrar;
    private javax.swing.JMenu MenuPesquisar;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
